#
# LA dependencies

# See: https://github.com/AtlasOfLivingAustralia/documentation/wiki/Dependencies#dependencies-list

# Module names should be these of: https://github.com/living-atlases/la-toolkit/blob/master/lib/models/LAServiceConstants.dart
# in order to be correctly parsed

alaInstall:
  '>= 2.0.3':
    - ansible: '2.10.3'

alerts:
  '>= 1.5.1':
    - regions: '>= 3.3.5'
    - alaHub: '>= 3.2.9'
    - bie: '>= 1.5.0'
  '>= 2.0.0':
    - java: '>= 11'

apikey:
  '>= 1.7.0':
    - cas: '>= 6.5.6-3'
    - casManagement: '>= 6.5.5-2'
    - userdetails: '>= 3.0.1'
    - java: '>= 11'

# ala-bie-hub uses bie too

bie:
  '> 2.0.1':
    - java: '>= 11'

biocacheService:
  '>= 2.5.0':
    - tomcat: '>= 9.0.0'
  # biocache-service 2.x uses biocache-store
  '>=2.7.0':
    - biocacheCli: '>= 2.6.1'
  # biocache-service 3.x uses pipelines
  '>= 3.0.0':
    - pipelines: 'any'

biocollect:
  'any':
    - alaInstall: '>= 2.1.7'
    - generator: '>= 1.2.32'

biocacheCli:
  'any':
    - solr: '< 8.0.0'
  '>= 2.4.5':
    - images: '>= 1.0.7'
  '< 3.0.0':
    - biocacheService: '< 3.0.0'

cas:
  '>= 6.5.6-3':
    - casManagement: '>= 6.5.5-2'
    - userdetails: '>= 3.0.1'
    - apikey: '>= 1.7.0'
    - java: '>= 11'

casManagement:
  '>= 6.5.5-2':
    - cas: '>= 6.5.6-3'
    - userdetails: '>= 3.0.1'
    - apikey: '>= 1.7.0'
    - java: '>= 11'

dashboard:
  '>= 2.2':
    - alaInstall: '>= 2.0.5'

doi:
  '>= 1.1':
    - biocacheService: '>= 2.5.0'
    - regions: '>= 3.3.4'

images:
  '>= 1.1':
    - alaInstall: '>= 2.0.8'

logger:
  '> 4.0.1':
    - java: '>= 11'

pipelines:
  'any':
    - biocacheService: '>= 3.0.0'
    - alaInstall: '>= 2.1.0'
    - solrcloud: '>= 8.9.0'
    - alaNameMatchingService: '>= 1.0.0'
    - images: '>= 1.1.1-7'

spatial:
  '>= 0.3.12':
    - spatialService: '> 0.3.12'

speciesLists:
  '< 4.0.0':
    - nameindexer: 'any'
  '>= 4.0.0':
    - namematchingService: 'any'

userdetails:
  '>= 3.0.1':
    - cas: '>= 6.5.6-3'
    - casManagement: '>= 6.5.5-2'
    - apikey: '>= 1.7.0'
    - java: '>= 11'

# From here la-toolkit and related:

toolkit:

  '>= 1.0.22 < 1.0.23':
    - alaInstall: '>= 2.0.6'
    - generator: '>= 1.1.36'

  '>= 1.0.23 < 1.1.0':
    - alaInstall: '>= 2.0.6'
    - generator: '>= 1.1.37'

  '>= 1.1.0 < 1.1.9':
    - alaInstall: '>= 2.0.7'
    - generator: '>= 1.1.43'

  '>= 1.1.9 < 1.1.26':
    - alaInstall: '>= 2.0.8'
    - generator: '>= 1.1.49'

  '>= 1.1.26 < 1.2.0':
    - alaInstall: '>= 2.0.10'
    - generator: '>= 1.1.51'

  '>= 1.2.0 < 1.2.1':
    - alaInstall: '>= 2.0.11'
    - generator: '>= 1.2.0'

  '>= 1.2.1 < 1.2.2':
    - alaInstall: '>= 2.0.11'
    - generator: '>= 1.2.1'

  '>= 1.2.2 < 1.2.6':
    - alaInstall: '>= 2.0.11'
    - generator: '>= 1.2.1'

  '>= 1.2.6 < 1.2.8':
    - alaInstall: '>= 2.0.11'
    - generator: '>= 1.2.2'

  '>= 1.2.8 < 1.3.0':
    - alaInstall: '>= 2.1.1'
    - generator: '>= 1.2.7'

  '>= 1.3.0 < 1.3.1':
    - alaInstall: '>= 2.1.2'
    - generator: '>= 1.2.9'

  '>= 1.3.1 < 1.3.2':
    - alaInstall: '>= 2.1.3'
    - generator: '>= 1.2.16'

  '>= 1.3.2 < 1.3.3':
    - alaInstall: '>= 2.1.4'
    - generator: '>= 1.2.20'

  '>= 1.3.3 < 1.3.4':
    - alaInstall: '>= 2.1.5'
    - generator: '>= 1.2.22'

  '>= 1.3.4 < 1.3.5':
    - alaInstall: '>= 2.1.5'
    - generator: '>= 1.2.22'

  '>= 1.3.5 < 1.3.6':
    - alaInstall: '>= 2.1.5'
    - generator: '>= 1.2.22'

  '>= 1.3.6 < 1.3.7':
    - alaInstall: '>= 2.1.6'
    - generator: '>= 1.2.29'

  '>= 1.3.7 < 1.3.8':
    - alaInstall: '>= 2.1.6'
    - generator: '>= 1.2.30'

  '>= 1.3.8 < 1.3.9':
    - alaInstall: '>= 2.1.7'
    - generator: '>= 1.2.33'

  '>= 1.3.9 < 1.3.10':
    - alaInstall: '>= 2.1.7'
    - generator: '>= 1.2.38'

  '>= 1.3.10 < 1.3.11':
    - alaInstall: '>= 2.1.9'
    - generator: '>= 1.2.46'

  '>= 1.3.11':
    - alaInstall: '>= 2.1.9'
    - generator: '>= 1.2.48'
